# Copyright (c) 2020  Mikhail Gordeev
#
# SPDX-License-Identifier: Apache-2.0

#alt: docker image to be used to create a rootfs
#@OS_VERSION@: Docker image version to build this dockerfile
from alt:@OS_VERSION@

# This dockerfile needs to provide all the componets need to build a rootfs
# Install any package need to create a rootfs (package manager, extra tools)

# RUN commands
RUN apt-get update && apt-get install -y \
    gcc \
    make \
    git \
    curl

# This will install the proper golang to build Kata components
@INSTALL_GO@
